# Plugin language.
#
# Available by default:
# - en_us
# - zh_cn
language: en_us

data:
  # Seconds between each automatic async data save.
  save-interval-seconds: 1800

  # Seconds between each automatic cleanup task.
  cleanup-interval-seconds: 300