name: FarmLimiter
version: 0.0.1
main: basementhost.randomchad.FarmLimiterPlugin
api-version: '26.1.2'
description: Limiting and nerfing farm scale and efficiency for balancing and server resources optimization
author: Random_Chad