name: FarmLimiter
version: 0.9.2
main: basementhost.randomchad.FarmLimiterPlugin
api-version: '26.1.2'
description: Limiting and nerfing farm scale and efficiency for balancing and server resources optimization
author: Random_Chad

commands:
  farmlimiter:
    description: Main command for FarmLimiter
    usage: /farmlimiter
    aliases:
      - fl
    permission: farmlimiter.use

permissions:
  farmlimiter.use:
    description: Allows using FarmLimiter basic commands
    default: op

  farmlimiter.admin:
    description: Allows using FarmLimiter admin commands
    default: op

  farmlimiter.breeding.bypass:
    description: Allows bypassing breeding limits.
    default: op